import { inter } from "./ui/styles/fonts";
import "./ui/styles/globals.css";

export const metadata = {
  title: "Helotes Haunted Gardens",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <footer style={{backgroundColor: 'orange', border: '1px solid white'}}>
        <p style={{color: 'black'}}>Contact info here</p>
      </footer>
    </html>
  );
}
